### PR TITLE
fix: descriptor mocking should require configurable and enumerable

### PR DESCRIPTION
**Pull request by popomore**

### CODE REVIEW

**Comment by fent** [comment]
Why require these properties? If `configurable: false` is given, then the mocked property can't be `muk.restore()`d, and it can't be mocked again.

**Comment by perzy** [comment]
With this scene, Should we add anthor api like `muk.getter、muk.setter` to support?

**Comment by fent** [comment]
Any update?

**Comment by fent** [comment]
Closing for inactivity

**Pull request closed without merging**
